google:
  url: postgres://postgres:zaqwsx@146.148.112.145:5432/postgres
  url-old: postgres://postgres:qwerty@146.148.2.81:5432/postgres

local:
  url: postgres://events_reader@localhost:5432/events
  writer:
    username: events_writer
    password: GJmVtmG6MJSDRseQEJcJ2gaU
